version: "3"
services:
  app:
    build: ./
    ports:
      - '5656:5656'
    volumes:
      - ./:/app
    environment: 
    - PSQL_URL=postgresql://short_line:QWERTY@db/short_line

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: short_line
      POSTGRES_PASSWORD: QWERTY
    volumes:
      - ./etc/sample_db:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    restart: unless-stopped